services:
  web_nginx: 
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./www:/www
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image: edsongsilva/phpserver8
    container_name: php-fpm
    volumes:
      - ./www:/www
    links:
      - db_nginx
  db_nginx:
    image: mysql:8.0.26
    container_name: mysql_nginx
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edsondb
  phpmyadmin_nginx:
    container_name: phpmyadmin_nginx
    image: phpmyadmin/phpmyadmin
    links:
      - db_nginx:db
    ports:
      - 8083:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

   
